pipeline: B
input_pdf: data/PS1101_245TB_AtomosP_E3_L_PDFSS_250715_R2.pdf
output_pdf: outputs/PS1101_245TB_AtomosP_E3_L_PDFSS_250715_R2_translated.pdf
working_dir: data/working
cleanup_working: false

ocr:
  enabled: true
  lang: kor+eng

translate:
  api_base: http://localhost:8000/v1
  model: llm
  api_key: 123
  batch_size: 10
  cache: cache/translations.json

layout:
  overflow_shrink_pct: 10
  font: Noto Sans
